language: php
php:
  - "5.4"

install:
   - composer --dev --profile --prefer-source install

# Unit tests
script: sh test/phpunit.sh

# Acceptance tests
before_script:
  - sudo apt-get install nginx
  - sudo service nginx start
  - sudo cp -f build/slim.dev /etc/nginx/sites-available/slim.dev
  - sudo ln -s /etc/nginx/sites-available/slim.dev /etc/nginx/sites-enabled/slim.dev
  - sudo sed -i 's/localhost/localhost slim.dev/g' /etc/hosts
  - sudo service nginx reload

script: sh test/behat.sh -p ci

notifications:
  email: "snepote@gmail.com"