language: php
php:
  - "5.4"

install:
   - composer --dev --profile --prefer-source install

# Acceptance tests
before_script:
  - sudo apt-get install php5-fpm
  - sudo apt-get install nginx
  - sudo cp -f ./config/nginx/travis.conf /etc/nginx/nginx.conf
  - sudo cp -f ./config/nginx/travis.vhost /etc/nginx/sites-available/default
  - sudo service nginx restart
  - curl localhost

script:
  - sh test/phpunit.sh
  - sh test/behat.sh -p ci

notifications:
  email: "snepote@gmail.com"