language: php
php:
  - "5.4"

install:
   - composer selfupdate
   - composer --dev --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - sudo apt-get install nginx
  - sudo cp -f ./config/nginx/travis.conf /etc/nginx/nginx.conf
  - sudo cp -f ./config/nginx/travis.vhost /etc/nginx/sites-available/default
  - sudo service nginx restart
  # php5 fpm
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

script:
  - sh test/phpunit.sh
  - sh test/behat.sh -p ci

notifications:
  email: "snepote@gmail.com"